[CmdletBinding()]
param([switch]$VerifyOnly)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$toolchain = [IO.Path]::GetFullPath((Join-Path $repo '..\..\toolchains\de-luau-toolchain\bin'))
$generated = Join-Path $PSScriptRoot 'generated'
New-Item -ItemType Directory -Path $generated -Force | Out-Null
$bytecode = Join-Path $generated 'callback_runtime.lua_B'
& (Join-Path $toolchain 'luau.exe') (Join-Path $PSScriptRoot 'verify_callback_runtime.luau')
if ($LASTEXITCODE) { throw 'Callback semantics tests failed' }
& (Join-Path $toolchain 'derecomp.exe') recompile (Join-Path $PSScriptRoot 'callback_runtime.luau') $bytecode
if ($LASTEXITCODE) { throw 'Callback DE compilation failed' }
foreach ($mode in @('de-roundtrip', 'semantic-ir-verify')) {
    & (Join-Path $toolchain 'derecomp.exe') $mode $bytecode
    if ($LASTEXITCODE) { throw "Callback $mode failed" }
}
$bytes = [IO.File]::ReadAllBytes($bytecode)
$lines = @('#pragma once', '// Generated by RENOVICE_TOOLCHAIN/injection/build_callback_runtime.ps1.', 'namespace renovice::injection {', 'inline constexpr unsigned char callback_runtime_bytecode[]{')
for ($i = 0; $i -lt $bytes.Length; $i += 16) {
    $last = [Math]::Min($i + 15, $bytes.Length - 1)
    $lines += ('    ' + (($bytes[$i..$last] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ',')
}
$lines += '};'
$u44Bytecode = Join-Path $generated 'callback_runtime.u44.lua_B'
& (Join-Path $toolchain 'derecomp.exe') recompile-u44 (Join-Path $PSScriptRoot 'callback_runtime.luau') $u44Bytecode
if ($LASTEXITCODE) { throw 'U44 helper compilation failed' }
& (Join-Path $toolchain 'derecomp.exe') de-roundtrip $u44Bytecode
if ($LASTEXITCODE) { throw 'U44 helper container roundtrip failed' }
$u44Bytes = [IO.File]::ReadAllBytes($u44Bytecode)
$lines += 'inline constexpr unsigned char callback_runtime_bytecode_u44[]{'
for ($i = 0; $i -lt $u44Bytes.Length; $i += 16) {
    $last = [Math]::Min($i + 15, $u44Bytes.Length - 1)
    $lines += ('    ' + (($u44Bytes[$i..$last] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ',')
}
$lines += '};', '}'
$content = ($lines -join "`n") + "`n"
$header = Join-Path $repo 'renovice\callback_runtime_bytecode.hpp'
if ($VerifyOnly) {
    if ([IO.File]::ReadAllText($header) -cne $content) { throw 'Embedded callback bytes differ from source' }
} else { [IO.File]::WriteAllText($header, $content, [Text.UTF8Encoding]::new($false)) }
Write-Output "CALLBACK EMBED PASS bytes=$($bytes.Length) sha256=$((Get-FileHash $bytecode -Algorithm SHA256).Hash)"
