[CmdletBinding()]
param([switch]$VerifyOnly)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$toolchain = [IO.Path]::GetFullPath((Join-Path $repo '..\..\toolchains\de-luau-toolchain\bin'))
$generated = Join-Path $PSScriptRoot 'generated'
New-Item -ItemType Directory -Path $generated -Force | Out-Null
$bytecode = Join-Path $generated 'callback_runtime.lua_B'
# luau.exe and derecomp.exe read short copies and write into the gate scratch
# folder (the repository may be deeper than MAX_PATH); results are copied to
# their repository paths exactly as the tools wrote them.
. (Join-Path (Split-Path $PSScriptRoot -Parent) 'gate_paths.ps1')
$scratch = Get-GateScratch $repo 'callback-runtime'
$shortDir = Join-Path (Copy-GateSources $repo $scratch @('RENOVICE_TOOLCHAIN\injection\callback_runtime.luau', 'RENOVICE_TOOLCHAIN\injection\verify_callback_runtime.luau')) 'RENOVICE_TOOLCHAIN\injection'
$shortSource = Join-Path $shortDir 'callback_runtime.luau'
$shortBytecode = Join-Path $scratch 'callback_runtime.lua_B'
& (Join-Path $toolchain 'luau.exe') (Join-Path $shortDir 'verify_callback_runtime.luau')
if ($LASTEXITCODE) { throw 'Callback semantics tests failed' }
& (Join-Path $toolchain 'derecomp.exe') recompile $shortSource $shortBytecode
if ($LASTEXITCODE) { throw 'Callback DE compilation failed' }
foreach ($mode in @('de-roundtrip', 'semantic-ir-verify')) {
    & (Join-Path $toolchain 'derecomp.exe') $mode $shortBytecode
    if ($LASTEXITCODE) { throw "Callback $mode failed" }
}
Copy-Item -LiteralPath $shortBytecode -Destination $bytecode -Force
$bytes = [IO.File]::ReadAllBytes($bytecode)
$lines = @('#pragma once', '// Generated by RENOVICE_TOOLCHAIN/injection/build_callback_runtime.ps1.', 'namespace renovice::injection {', 'inline constexpr unsigned char callback_runtime_bytecode[]{')
for ($i = 0; $i -lt $bytes.Length; $i += 16) {
    $last = [Math]::Min($i + 15, $bytes.Length - 1)
    $lines += ('    ' + (($bytes[$i..$last] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ',')
}
$lines += '};'
$u44Bytecode = Join-Path $generated 'callback_runtime.u44.lua_B'
$shortU44Bytecode = Join-Path $scratch 'callback_runtime.u44.lua_B'
& (Join-Path $toolchain 'derecomp.exe') recompile-u44 $shortSource $shortU44Bytecode
if ($LASTEXITCODE) { throw 'U44 helper compilation failed' }
& (Join-Path $toolchain 'derecomp.exe') de-roundtrip $shortU44Bytecode
if ($LASTEXITCODE) { throw 'U44 helper container roundtrip failed' }
Copy-Item -LiteralPath $shortU44Bytecode -Destination $u44Bytecode -Force
$u44Bytes = [IO.File]::ReadAllBytes($u44Bytecode)
$lines += 'inline constexpr unsigned char callback_runtime_bytecode_u44[]{'
for ($i = 0; $i -lt $u44Bytes.Length; $i += 16) {
    $last = [Math]::Min($i + 15, $u44Bytes.Length - 1)
    $lines += ('    ' + (($u44Bytes[$i..$last] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ',')
}
$lines += '};', '}'
$content = ($lines -join "`n") + "`n"
$header = Join-Path $repo 'renovice\callback_runtime_bytecode.hpp'
if ($VerifyOnly) {
    if ([IO.File]::ReadAllText($header) -cne $content) { throw 'Embedded callback bytes differ from source' }
} else { [IO.File]::WriteAllText($header, $content, [Text.UTF8Encoding]::new($false)) }
Write-Output "CALLBACK EMBED PASS bytes=$($bytes.Length) sha256=$((Get-FileHash $bytecode -Algorithm SHA256).Hash)"
