[CmdletBinding()]
param([switch]$VerifyOnly)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$toolchain = [IO.Path]::GetFullPath((Join-Path $repo '..\..\toolchains\de-luau-toolchain\bin'))
$generated = Join-Path $PSScriptRoot 'generated'
New-Item -ItemType Directory -Path $generated -Force | Out-Null
$bytecode = Join-Path $generated 'automatic_damage_runtime.lua_B'
$source = Join-Path $PSScriptRoot 'automatic_damage_runtime.luau'
$canonicalBattleLog = Join-Path $repo 'RENOVICE_SCRIPTING\DIAGNOSTICS\CombatTransactionBattleLogV5.luau'
$sourceText = [IO.File]::ReadAllText($source).Replace("`r`n", "`n")
$canonicalText = [IO.File]::ReadAllText($canonicalBattleLog).Replace("`r`n", "`n").TrimEnd("`n") + "`n"
$observerMarker = '-- Automatic scripted-damage observer.'
$observerOffset = $sourceText.IndexOf($observerMarker, [StringComparison]::Ordinal)
if ($observerOffset -lt 0 -or $sourceText.Substring(0, $observerOffset) -cne $canonicalText) {
    throw 'Embedded automatic damage runtime no longer contains the exact canonical Battle Log V5 prefix'
}

& (Join-Path $toolchain 'luau.exe') (Join-Path $PSScriptRoot 'verify_automatic_damage_runtime.luau')
if ($LASTEXITCODE) { throw 'Automatic damage runtime semantics tests failed' }
& (Join-Path $toolchain 'derecomp.exe') recompile $source $bytecode
if ($LASTEXITCODE) { throw 'Automatic damage runtime DE compilation failed' }
foreach ($mode in @('de-roundtrip', 'semantic-ir-verify')) {
    & (Join-Path $toolchain 'derecomp.exe') $mode $bytecode
    if ($LASTEXITCODE) { throw "Automatic damage runtime $mode failed" }
}

$bytes = [IO.File]::ReadAllBytes($bytecode)
$lines = @(
    '#pragma once',
    '// Generated by RENOVICE_TOOLCHAIN/injection/build_automatic_damage_runtime.ps1.',
    'namespace renovice::injection {',
    'inline constexpr unsigned char automatic_damage_runtime_bytecode[]{'
)
for ($i = 0; $i -lt $bytes.Length; $i += 16) {
    $last = [Math]::Min($i + 15, $bytes.Length - 1)
    $lines += ('    ' + (($bytes[$i..$last] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ',')
}
$lines += '};'
$u44Bytecode = Join-Path $generated 'automatic_damage_runtime.u44.lua_B'
& (Join-Path $toolchain 'derecomp.exe') recompile-u44 $source $u44Bytecode (Join-Path $toolchain '..\profiles\u44\name-map.tsv')
if ($LASTEXITCODE) { throw 'U44 helper compilation failed' }
& (Join-Path $toolchain 'derecomp.exe') de-roundtrip $u44Bytecode
if ($LASTEXITCODE) { throw 'U44 helper container roundtrip failed' }
$u44Bytes = [IO.File]::ReadAllBytes($u44Bytecode)
$lines += 'inline constexpr unsigned char automatic_damage_runtime_bytecode_u44[]{'
for ($i = 0; $i -lt $u44Bytes.Length; $i += 16) {
    $last = [Math]::Min($i + 15, $u44Bytes.Length - 1)
    $lines += ('    ' + (($u44Bytes[$i..$last] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ',')
}
$lines += '};', '}'
$content = ($lines -join "`n") + "`n"
$header = Join-Path $repo 'renovice\automatic_damage_runtime_bytecode.hpp'
if ($VerifyOnly) {
    if (-not (Test-Path -LiteralPath $header -PathType Leaf) -or
            [IO.File]::ReadAllText($header) -cne $content) {
        throw 'Embedded automatic damage bytes differ from source'
    }
} else {
    [IO.File]::WriteAllText($header, $content, [Text.UTF8Encoding]::new($false))
}
Write-Output "AUTOMATIC DAMAGE EMBED PASS bytes=$($bytes.Length) sha256=$((Get-FileHash $bytecode -Algorithm SHA256).Hash)"
